# Generated by Django 4.2.7 on 2024-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
