# Generated by Django 4.2.7 on 2024-04-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ride_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('mobie_number', models.CharField(max_length=255)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=255)),
            ],
        ),
    ]
